# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
#       - name: Update themes
#         run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          
      - name: build
        run: hugo 
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: thphuc273/thienphuc.github.io
          publish_dir: ./public
          # user_name: thienphuc
          # user_email: thphucnguyen2703@gmail.com
          publish_branch: master
          allow_empty_commit: true
